name: Suíte de Testes - SUT API
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Subir infraestrutura (Docker Compose)
        run: docker compose up -d

      - name: Demand Service
        working-directory: ./demand-service
        run: npm install

      - name: Executar testes automatizados (Vitest)
        working-directory: ./demand-service
        run: npx vitest run